"""rename game sessions table

Revision ID: e95c73ae611c
Revises: a46c59a60aa0
Create Date: 2024-05-05 16:06:21.403730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e95c73ae611c"
down_revision: Union[str, None] = "a46c59a60aa0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_sessions",
        sa.Column("game_mode", sa.String(), nullable=False),
        sa.Column("examples_category", sa.Integer(), nullable=False),
        sa.Column("total_count_examples", sa.Integer(), nullable=False),
        sa.Column("correct_count_examples", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("gamesessions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gamesessions",
        sa.Column("game_mode", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "examples_category", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "total_count_examples", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "correct_count_examples", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="gamesessions_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="gamesessions_pkey"),
    )
    op.drop_table("game_sessions")
    # ### end Alembic commands ###
