"""add Achievement association table

Revision ID: 689ae6e805b6
Revises: 1f60ed6049aa
Create Date: 2024-06-07 13:32:31.566480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '689ae6e805b6'
down_revision: Union[str, None] = '1f60ed6049aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements_associations',
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('achievement_id', 'user_id', 'id')
    )
    op.drop_table('achievements_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements_association',
    sa.Column('achievement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name='achievements_association_achievement_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='achievements_association_user_id_fkey')
    )
    op.drop_table('achievements_associations')
    # ### end Alembic commands ###
