"""add Achievement association table

Revision ID: 0fbc69ab2798
Revises: 689ae6e805b6
Create Date: 2024-06-07 13:48:51.824782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fbc69ab2798'
down_revision: Union[str, None] = '689ae6e805b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achievements_associations')
    op.add_column('users', sa.Column('achievements_ids', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'achievements', ['achievements_ids'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'achievements_ids')
    op.create_table('achievements_associations',
    sa.Column('achievement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name='achievements_associations_achievement_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='achievements_associations_user_id_fkey'),
    sa.PrimaryKeyConstraint('achievement_id', 'user_id', 'id', name='achievements_associations_pkey')
    )
    # ### end Alembic commands ###
