"""create game sessions table

Revision ID: a46c59a60aa0
Revises: 7cc16f5d80de
Create Date: 2024-05-05 15:58:57.581099

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a46c59a60aa0"
down_revision: Union[str, None] = "7cc16f5d80de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gamesessions",
        sa.Column("game_mode", sa.String(), nullable=False),
        sa.Column("examples_category", sa.Integer(), nullable=False),
        sa.Column("total_count_examples", sa.Integer(), nullable=False),
        sa.Column("correct_count_examples", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_table("gamesessions")
    # ### end Alembic commands ###
