"""update table game sessions and add table rating

Revision ID: f8cc887a93de
Revises: 5e58457cd4b9
Create Date: 2024-06-06 12:40:18.179042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8cc887a93de'
down_revision: Union[str, None] = '5e58457cd4b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ratings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'user_id')
    # ### end Alembic commands ###
