"""update table game sessions and add table rating

Revision ID: 1584e60aaa17
Revises: f8cc887a93de
Create Date: 2024-06-06 12:41:31.956252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1584e60aaa17'
down_revision: Union[str, None] = 'f8cc887a93de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
