"""add Achievement association table

Revision ID: d2c88d8fdd8f
Revises: 0fbc69ab2798
Create Date: 2024-06-07 13:53:46.789479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c88d8fdd8f'
down_revision: Union[str, None] = '0fbc69ab2798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'achievements_ids',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'achievements_ids',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
