"""update table ratings

Revision ID: 3cfccde13684
Revises: 1584e60aaa17
Create Date: 2024-06-06 13:07:25.658773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cfccde13684'
down_revision: Union[str, None] = '1584e60aaa17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('correct_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'correct_count')
    # ### end Alembic commands ###
